global:
  ENVIRONMENT: "Development"
  namespace: mateapp

mysql:
  configs:
    secrets:
      MYSQL_ROOT_PASSWORD: placeholder
      MYSQL_USER: placeholder
      MYSQL_PASSWORD: placeholder
kube2py:
  image:
    name: kube2py
    repository: volodymyrdv/kube2py
    version: 2.0.0

  configs:
    EXTERNAL_ENDPOINT: "http://httpbin-api.mateapp.svc.cluster.local"
    PORT: "8080"
    APP_ENV: "testing-helm"

  secrets:
    password: placeholder
    login: placeholder
    external_endpoint: http://httpbin-api.mateapp.svc.cluster.local
    DB_CONNECTION: placeholder

  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 4
    cpu:
      averageUtilization: 70
    memory:
      averageUtilization: 70

  resources:
    requests:
      memory: "64Mi"
      cpu: "30m"
    limits:
      memory: "64Mi"
      cpu: "30m"
