apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Values.namespace }}
data:
  environment: {{ .Values.global.ENVIRONMENT }}
  init.sql: |
    GRANT ALL PRIVILEGES ON app_db.* TO 'app_user'@'%';

    USE app_db;

    CREATE TABLE counter (
      id INT PRIMARY KEY AUTO_INCREMENT,
      value INT NOT NULL
    );
