apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.configs.secrets }}
  {{ $key }}: {{ printf "%v" $value | b64enc | quote }}
{{- end }}
