global:
  ENVIRONMENT: "Staging"

kube2py:
  configs:
    ENVIRONMENT: "Staging"
    APP_ENV: "testing-helm-staging"

  secrets:
    password: MyStrongerPassword
    login: SuperUser

  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3

  resources:
    requests:
      memory: "64Mi"
      cpu: "30m"
    limits:
      memory: "64Mi"
      cpu: "30m"
